[package]
name = "dirt"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.4", features = ["full"] }
thiserror = "2"
socket2 = "0.5.8"
xtra = { version = "0.6.0", features = ["tokio", "macros"] }
